#FROM mysql:latest
#ENV MYSQL_DATABASE=cursoEF
#ENV MYSQL_USER=cursoEFuser
#ENV MYSQL_PASSWORD=cursoEFpass
#ENV MYSQL_ROOT_PASSWORD=cursoEFpass

# mysql is not working with concurrencycheck
FROM postgres:latest

ENV POSTGRES_USER=cursoEFuser
ENV POSTGRES_PASSWORD cursoEFpass
ENV POSTGRES_DB cursoEF